### PR TITLE
Validate types with tsc without skipLibCheck option + introduce type declaration checking

### PR DESCRIPTION
**Pull request by cmdoptesc**
Hi Vova, I experienced a number of type errors when I imported the @anycable/web package into my codebase, but didn't notice the errors when I pulled down anycable-client and ran `yarn tsc`. Realized it was because `skipLibCheck` in tsconfig.json had skipped checking the type declaration files (*.d.ts) in this repo.

* fixed all the errors by disabling the [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) flag
* still need skipLibCheck for [check-dts](https://github.com/ai/check-dts) to pass due to errors from `AbortController` and `AbortSignal`, so added it back to tsconfig.json after I was done
* added a separate typecheck with `tsc` using a different config (noskiplibcheck_tsconfig.json) that will check the type declarations in this repo

### CODE REVIEW

**Comment by palkan** [comment]
Great! Thanks!

Could you please take a look at CI failures?

**Comment by cmdoptesc** [comment]
@palkan is there a way for me to kick off another CI run, or can only you do that?

**Comment by palkan** [comment]
> is there a way for me to kick off another CI run, or can only you do that?

It's only me for first-time PRs; as soon as we get this merged, all your subsequent PRs will run automatically.

**Comment by palkan** [comment]
Looks like we need to add some configuration to ignore `node_modules/**/*` and `**/error.ts` files from type checking.

**Comment by cmdoptesc** [comment]
Hmmm, I had trouble trying to repro the type failures on the CI run because my local tests can't get that far in the process due to import issues. I think the type failures on CI stem from the `check-dts` step.

That didn't fail before because `skipLibCheck` was included.

Because we only care about the outputs from the `packages` directory, I propose we change the check to `check-dts 'packages/**/*'`. What do you think?

Running that command locally emits only the type failures in `packages/core/channel/errors.ts`; similar to what is on CI. Those failures are related to the swapping the position of the `[Parameters<ActionsType[A]>[0]]` type (e0224d2e). I'm assuming that the behavior modeled in [channel/errors.ts](https://github.com/anycable/anycable-client/blob/9512487dec3780dd1d5125537479b6e392010d3b/packages/core/channel/errors.ts#L76) is correct and we should work from that.

I'll try to look into that change more this afternoon, but if you have any spare time on your end, I'd love a second set of eyes on fixing this declaration: https://github.com/anycable/anycable-client/blob/9512487dec3780dd1d5125537479b6e392010d3b/packages/core/channel/index.d.ts#L67

**Comment by cmdoptesc** [comment]
@palkan can I please trouble you to kick off another CI run?

Also, the last commit with introducing a secondary typescript config file may be a bit controversial. I wish the logic was inverted where `check-dts` could take in an explicit option to skip declaration files, and `tsc` could just rely on the default tsconfig.json file.

**Comment by palkan** [comment]
Thanks!

Upgrading `@types/node` fixed the problem with `check-dts`, so we don't need a separate config.

**Pull request merged**
